/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    Container: typeof import('./src/components/common/Container.vue')['default']
    DatePickerInput: typeof import('./src/components/ui/DatePickerInput.vue')['default']
    HistoryToolbar: typeof import('./src/components/todo/history/HistoryToolbar.vue')['default']
    IconButton: typeof import('./src/components/ui/IconButton.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortToggle: typeof import('./src/components/todo/common/SortToggle.vue')['default']
    TodoAddButton: typeof import('./src/components/todo/home/TodoAddButton.vue')['default']
    TodoAddForm: typeof import('./src/components/todo/home/TodoAddForm.vue')['default']
    TodoDateLabel: typeof import('./src/components/todo/common/TodoDateLabel.vue')['default']
    TodoInlineEditor: typeof import('./src/components/todo/home/TodoInlineEditor.vue')['default']
    TodoItemHistory: typeof import('./src/components/todo/history/TodoItemHistory.vue')['default']
    TodoItemHome: typeof import('./src/components/todo/home/TodoItemHome.vue')['default']
    TodoItemLayout: typeof import('./src/components/todo/common/TodoItemLayout.vue')['default']
    TodoList: typeof import('./src/components/todo/common/TodoList.vue')['default']
    TodoListHistory: typeof import('./src/components/todo/history/TodoListHistory.vue')['default']
    TodoListHome: typeof import('./src/components/todo/home/TodoListHome.vue')['default']
    TodoMarker: typeof import('./src/components/todo/common/TodoMarker.vue')['default']
    TodoStatusBadge: typeof import('./src/components/todo/common/TodoStatusBadge.vue')['default']
    TodoSummary: typeof import('./src/components/todo/home/TodoSummary.vue')['default']
  }
}
